version: "3.8"

networks:
  net_ext:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
  net_dmz:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.10.20.0/24
  net_deep:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.10.30.0/24
  net_inner:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.10.40.0/24

services:
  target01:
    image: ubuntu:latest
    hostname: target01
    container_name: target01
    networks:
      net_ext:
        ipv4_address: 10.10.10.5
      net_dmz:
        ipv4_address: 10.10.20.5
    command: >
      /bin/sh -c "apt-get update && apt-get install -y iproute2 iputils-ping curl ssh openssh-server socat proxychains4 && mkdir -p /run/sshd && /usr/sbin/sshd && sleep infinity"

  target02:
    image: ubuntu:latest
    hostname: target02
    container_name: target02
    networks:
      net_dmz:
        ipv4_address: 10.10.20.6
      net_deep:
        ipv4_address: 10.10.30.6
    command: >
      /bin/sh -c "apt-get update && apt-get install -y iproute2 iputils-ping curl ssh openssh-server socat proxychains4 && mkdir -p /run/sshd && /usr/sbin/sshd && sleep infinity"

  target03:
    image: dockur/windows
    hostname: target03_windows
    container_name: target03
    privileged: true
    environment:
      VERSION: "11"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
    cap_add:
      - NET_ADMIN
    networks:
      net_deep:
        ipv4_address: 10.10.30.7
      net_inner:
        ipv4_address: 10.10.40.7
    volumes:
      - ./windows-oem:/oem

  target04:
    image: ubuntu:latest
    hostname: target04
    container_name: target04
    networks:
      net_inner:
        ipv4_address: 10.10.40.8
    command: >
      /bin/sh -c "apt-get update && apt-get install -y iproute2 iputils-ping curl ssh openssh-server socat proxychains4 && mkdir -p /run/sshd && echo 'FLAG{p1v0t_m4st3r_l1nux_f1n4l_fl4g}' > /root/flag.txt && echo 'FLAG{p1v0t_m4st3r_l1nux_f1n4l_fl4g}' > /home/flag.txt && useradd -m -s /bin/bash pivotuser && echo 'pivotuser:pivotpass' | chpasswd && echo 'root:rootpass' | chpasswd && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && /usr/sbin/sshd && sleep infinity"
